export const categories = [
  'Musikfestival',
  'Yoga Kongress',
  'Gutscheine',
  'Yoga Vidya Verlag',
  'E-Books',
  'Bücher',
  'Bestseller',
  'Zeitschriften',
  'Kalender',
  'CDs',
  'DVDs',
  'Yogapraxis',
  'Yogatherapie',
  'Ätherische & Aroma-Öle',
  'Ayurveda Produkte',
  'Naturkosmetik',
  'Murtis & Malas',
  'Klanginstrumente',
  'Räuchersortiment',
  'Poster & Cards',
  'Schmuck',
  'Mehr schöne Dinge',
  'Sale',
];
