export const categories = [
  { name: 'Musikfestival' },
  { name: 'Yoga Kongress' },
  { name: 'Gutscheine' },
  { name: 'Yoga Vidya Verlag', unterkategorien: ['Bücher', 'E-Books', 'CDs', 'DVDs', 'mp3 Download', 'Poster', 'Übungspläne', 'Grußkarten', 'Lesezeichen'] },
  { name: 'E-Books' },
  { name: 'Bücher', unterkategorien: ['Geschichten & Romane', 'Gesundheit & Heiltechniken', 'Karma & Reinkarnation', 'Kartensets', 'Kundalini & Energiearbeit', 'Mantra & Klang', 'Massage', 'Pranayama & Atem', 'Yoga Vidya Bücher', 'Hatha Yoga', 'Yogatherapie', 'Kinder & Yoga', 'Meditation', 'Swami Sivananda', 'Spirituelle Meister', 'Sanskrit', 'Philosophie & Mythologie', 'Naturspiritualität', 'Chakras & Mudras', 'Ayurveda Bücher', 'Spirituell Leben', 'Kochen & Ernährung', 'Mangalam Books', 'English & Pусский']},
  { name: 'Bestseller' },
  { name: 'Zeitschriften' },
  { name: 'Kalender' },
  { name: 'CDs', unterkategorien: ['Yogapraxis', 'Mantra & Kirtan', 'Für Kinder', 'Meditation & Entspannung', 'Meditative Musik', 'Global Pop & Weltmusik', 'Hörspiele & Hörbücher', 'Gemafreie Musik']},
  { name: 'DVDs' },
  { name: 'Yogapraxis', unterkategorien: ['Yogamatten', 'Yoga Zubehör', 'Yoga- & Meditationskissen', 'Yoga Sets', 'Yoga Hilfsmittel', 'Yoga Reinigung', 'Yoga Übungspläne', 'Yogamatten Ratgeber']},
  { name: 'Yogatherapie' },
  { name: 'Ätherische & Aroma-Öle', unterkategorien: ['Primavera', 'Wadi']},
  { name: 'Ayurveda Produkte' },
  { name: 'Naturkosmetik', unterkategorien: ['Gesichtspflege', 'Haarpflege', 'Körperpflege']},
  { name: 'Murtis & Malas', unterkategorien: ['Malas / Gebetsketten', 'Statuen & Murtis', 'Om Symbole']},
  { name: 'Klanginstrumente', unterkategorien: ['Klangschalen & Klöppel', 'Koshi Klangspiele', 'Zaphir Klangspiele']},
  { name: 'Räuchersortiment', unterkategorien: ['Nimi Räucherstäbchen', 'Harze, Kampfer, Zubehör']},
  { name: 'Poster & Cards', unterkategorien: ['Poster', 'Postkarten', 'Engelkarten', 'Shakticards', 'Mandala Karten', 'Der kleine Yogi']},
  { name: 'Schmuck' },
  { name: 'Mehr schöne Dinge', unterkategorien: ['Blankbooks', 'Fensterbilder', 'Lesezeichen', 'Wunschfähnchen', 'Yogi-Kissen', 'Stempel']},
  { name: 'Sale' },
];
